receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317        # OTLP gRPC endpoint
      http:
        endpoint: 0.0.0.0:4318        # OTLP HTTP endpoint (used by Spring Boot)

processors:
  batch: {}                           # Required for efficient exporting

exporters:
  debug:
    verbosity: detailed               # Optional: remove in production

  # Uncomment the following exporters to enable AWS X-Ray and CloudWatch exporting
  # awsxray:
  #   region: "us-east-1"               # X-Ray traces

  # awsemf:
  #   region: "us-east-1"
  #   log_group_name: "/spring/metrics" # Change to your CloudWatch log group
  #   namespace: "opentelemetry"        # CloudWatch metrics namespace


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug] # [awsxray, debug]  # Uncomment awsxray to enable X-Ray exporting

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug] # [awsemf, debug]  # Uncomment awsemf to enable CloudWatch exporting 
