name: Release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/spring-data-valkey
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Start Valkey
        run: |
          make start PROJECT=valkey VERSION=8.1.1 GH_ORG=valkey-io

      - name: Test and package Spring Data Valkey
        run: |
          ./mvnw -s settings.xml \
            -Ddevelocity.storage.directory=$HOME/.develocity-root \
            -Dmaven.repo.local=$HOME/.m2/spring-data-valkey \
            package javadoc:jar test \
            -Pnone \
            -DrunLongTests=true \
            -Dvalkey.server.version=8.1.1 \
            -U -B

      - name: Install Spring Data Valkey
        run: |
          ./mvnw -s settings.xml \
            -Ddevelocity.storage.directory=$HOME/.develocity-root \
            -Dmaven.repo.local=$HOME/.m2/spring-data-valkey \
            install -DskipTests \
            -Dgpg.skip=true \
            -B

      - name: Test and package Spring Boot Starter
        run: |
          cd spring-boot-starter-data-valkey
          ../mvnw -s ../settings.xml \
            -Ddevelocity.storage.directory=$HOME/.develocity-root \
            -Dmaven.repo.local=$HOME/.m2/spring-data-valkey \
            package javadoc:jar test \
            -U -B

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            target/*.jar
            spring-boot-starter-data-valkey/target/*.jar
          generate_release_notes: true
